apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: staging
  creationTimestamp: null
  labels:
    app: web-app
  name: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: web-app
    spec:
      containers:
      - image: web-app:1.0
        name: web-app
        resources: {}
status: {}