apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app 
  namespace: staging
  labels:
    app: web 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web 
  template:
    metadata:
      labels:
        app: web 
    spec:
      containers:
      - name: web 
        image: web-app:1.0 
        ports:
        - containerPort: 80