apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: production 
  creationTimestamp: null
  labels:
    app: myapp
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: myapp
    spec:
      containers:
      - image: nginx:latest
        name: nginx
        ports:
        - containerPort: 8080
status: {}

---

apiVersion: v1
kind: Service
metadata:
  namespace: production
  name: myapp-service
spec:
  selector:
    app: myapp
  ports:
    - port: 80
      targetPort: 8080
  externalTrafficPolicy: Local
  type: LoadBalancer