apiVersion: v1
kind: Service
metadata:
  name: myapp-service 
  namespace: production
spec:
  selector:
    app: myapp
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080 