apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      nodeSelector:
        role: backend
      containers:
      - name: backend-container
        image: classdevop/backend:v1