kind: ClusterRole
metadata:
  name: dev-cr
rules:
- apiGroups: ["*"]
  verbs: ["get", "watch", "list", "create"]
  resources: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cr-binding
subjects:
- kind: User
  name: developer
  apiGroup: rbac.authorization.k8s.io
- kind: Group
  name: dev 
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: dev-cr
  apiGroup: rbac.authorization.k8s.io