apiVersion: v1
kind: Namespace
metadata:
  name: finance
---  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-app
  namespace: finance
spec:
  replicas: 2
  selector:
    matchLabels:
      app: billing-app
  template:
    metadata:
      labels:
        app: billing-app
    spec:
      containers:
      - name: billing-app
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: policy-finance
  namespace: finance
spec:
  podSelector:
    matchLabels:
      app: billing-app
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: finance