apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-fast-storage
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: fast-storage
  hostPath:
    path: /mnt/data/fast-storage

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-fast-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: fast-storage

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database-app
  template:
    metadata:
      labels:
        app: database-app
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest
        volumeMounts:
        - mountPath: /data
          name: database-storage
      volumes:
      - name: database-storage
        persistentVolumeClaim:
          claimName: pvc-fast-storage