apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: aW1hbm11cXJpMQ==
  POSTGRES_DB: cG9zdGdyZXM=
  POSTGRESS_HOST: cG9zdGdyZXM=