apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: data-processing
  name: data-processing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-processing
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: data-processing
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app: data-processing
            topologyKey: kubernetes.io/hostname
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app: web-server
            topologyKey: kubernetes.io/hostname
      containers:
      - image: nginx
        name: nginx
